# Generated by Django 4.0.4 on 2022-05-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_medica',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
